#! /bin/sh

killall compton
sxhkd &
compton &
$HOME/.config/polybar/launch.sh
# pulseaudio --kill
# pulseaudio --start
# ckb-next --background &
kquitapp5 plasmashell

feh --bg-fill $HOME/Pictures/Wallpapers/daylight-environment-forest-idyllic-459225.jpg

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap          12
bspc config top_padding 20
bspc config bottom_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

##################
##### colors #####
##################

# Manjaro Green
bspc config normal_border_color "#2C2C2C"
bspc config active_border_color "#2C2C2C"
bspc config focused_border_color "#1ABC9C"

# Arc Dark
bspc config normal_border_color "#383C4A"
bspc config active_border_color "#383C4A"
bspc config focused_border_color "#5294E2"

##################
## window rules ##
##################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a yakuake manage=off state=floating layer=above

## KDE Plasma
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off

